## Applied Tax Resource (Base Resource)

### Properties

- `rate` (number): 9.35
- `name`: `TN`
- `amount` (number): 1.7765
- `apply_to_handling` (boolean): true
- `apply_to_shipping` (boolean): true
- `is_future_tax` (boolean): false
- `shipto`
- `date_created`
- `date_modified`