## Attribute Base Resource (object)

### Properties

- visibility (string): private
- name (string, required)
- value (string, required)

## Attribute Resource (Base Resource)

### Properties

- Include Attribute Base Resource 
- date_created
- date_modified