## Cart Template Base Resource (object)

### Properties
- `description` (required): `Cart Template`
- `content`
- `content_url`

## Cart Template Resource (Base Resource)

### Properties
- Include Cart Template Base Resource
- date_created
- date_modified