## Cart Base Resource (object)

### Properties

- `customer_uri`: `https://api.foxycart.com/customers/8`
- `total_shipping`: 0
- `total_future_shipping`: 0


## Cart Resource (Base Resource)

### Properties

- Include Cart Base Resource
- `total_item_price`: 0
- `total_tax`: 0
- `total_order`: 0
- date_created
- date_modified