## Client Resource (Base Resource)

### Properties

- client_secret
- date_created
- date_modified
- Include Client Base Resource 

## Client Base Resource (object)

### Properties

- client_id (string)
- redirect_uri (string, required): http://example.com
- `javascript_origin_uri` (string, required)
- project_name: Example Project
- project_description: `A really cool project using the API to make awesome. Lots - nd lots of awesome. Oh, and money too. People like money.`
- company_name (required): Super amazing company
- company_url: http://example.com
- company_logo (string)
- contact_name (required): John Doe
- contact_email (required): john.doe@example.com
- contact_phone (required): `555-555-5555`