## Collection Resource (object)
A collection of resources. You can easily paginate through this collection using the hypermedia links provided and the link relationships of first, prev, next, and last.

### Properties

- `_links` (object)
    - first (Link)
    - prev (Link)
    - next (Link)
    - last (Link)
    - *relation* (Link)
    
- `_embedded`
    - *relation* (Embedded)
- `total_items`: '5'
- `returned_items`: 5
- `limit`: 20
- `offset`: 0
