## Coupon Item Category Base Resource (object)

### Properties

- coupon_uri: `https://api-sandbox.foxycart.com/coupons/813`
- `item_category_uri`: `https://api-sandbox.foxycart.com/item_categories/307`


## Coupon Item Category Resource (Base Resource)

### Properties

- Include Coupon Item Category Base Resource 
- date_created
- date_modified