## Coupon Code Base Resource (object)

### Properties

- code (required): foo

## Coupon Code Resource (Base Resource)

### Properties

- Include Coupon Code Base Resource
- `number_of_uses_to_date`: 0
- date_created: 2015-05-21T14:46:15-0700
- date_modified: 2015-05-21T14:46:15-0700