## Default Template Resource (Base Resource)

### Properties
- message: `These are the default templates used for the cart, checkout, receipt and emails.`
- values (object)
    - *rel (string)* (object)        
        - content
        - content_url