## Discount Resource (Base Resource)

### Properties

- `code`: `tester`
- `amount` (number): -1
- `name`: `tester`
- `display`: `-1.00`
- `is_taxable` (boolean): false
- `is_future_discount` (boolean): false
- `date_created`
- `date_modified`