## Downloadable Base Resource (object)

### Properties

- `item_category_uri` (required): `https://api-sandbox.foxycart.com/item_categories/307`
- `name` (required): `Unicorn`
- `code` (required): `unicorn`
- `price` (number): 10

## Downloadable Resource (Base Resource)

### Properties

- Include Downloadable Base Resource 
- `file_name`: `unicorn_web.png`
- `file_size`: 267069
- `upload_date`: `2015-04-16T09:33:28-0700`
- `date_created`: `2015-04-16T09:33:28-0700`
- `date_modified`: `2015-04-16T09:46:46-0700`