## Email Template Base Resource (object)

### Properties
- `description` (required): `Email Receipt Template`
- `subject`
- `content_html`
- `content_html_url`
- `content_text`
- `content_text_url`

## Email Template Resource (Base Resource)

### Properties
- Include Email Template Base Resource
- date_created
- date_modified