## Error Entry Base Resource (object)

### Properties
- `hide_error` (boolean): false

## Error Entry Resource (Base Resource)

### Properties
- Include Error Entry Base Resource
- `url`: `https://api-sandbox.foxycart.com/api_rest.php`
- `error_message`: `DataFeed Failed: (2) 2012-08-10 12:12:49 No data returned for  [0]\n<url> malformed`
- `user_agent`: `curl/7.21.3 (i386-pc-win32) libcurl/7.21.3 OpenSSL/0.9.8q zlib/1.2.5`
- `referrer`
- `ip_address`: `10.1.249.103`
- `ip_country`
- `post_values`
- `get_values`
- date_created
- date_modified