## Fraud Protection Base Resource (object)

### Properties

- description : "Default Min Fraud"
- `score_threshold_reject` : 24
 
## Fraud Protection Resource (Base Resource)

### Properties

- Include Fraud Protection Base Resource 
- date_created
- date_modified