## Integration Resource (Base Resource)

### Properties

- user_uri: https://api-sandbox.foxycart.com/users/2
- client_id: super_duper_client_id
- scope: user_full_access store_id_8 store_full_access
- expires: 2147483647
- project_name: My Super Project
- project_description: A really cool project you should be excited about.
- company_name: FoxyCart
- company_url: http://www.foxycart.com
- company_logo: http://www.foxycart.com/assets/templates/v02/slices/foxycart-seo-ecommerce.png
- contact_name: Firstname Lastname
- contact_email: example@example.com
- `added_by_name`: Mada Baragau
- `added_by_email`: mada_baragau@yahoo.com