## Item Base Resource (object)

### Properties

- `item_category_uri`: `https://api-sandbox.foxycart.com/item_categories/1`
- `name` (required): `good stuff UPDATED`
- `price` (required, number): 15
- `quantity` (number): 5
- `quantity_min` (number): 0
- `quantity_max` (number): 0
- `weight` (number): 0.1
- `code`
- `parent_code`
- `discount_name`
- `discount_type`
- `discount_details`
- `subscription_frequency`
- `subscription_start_date`
- `subscription_next_transaction_date`
- `subscription_end_date`
- `shipto`
- `url`
- `image`
- `length` (number): 0
- `width` (number): 0
- `height` (number): 0
- `expires` (number): 0

## Item Resource (Base Resource)

### Properties

- Include Item Base Resource 
- `is_future_line_item` (boolean): false
- date_created
- date_modified