## Language Override Base Resource (object)

### Properties

- code (required): cart_caption
- gateway
- custom_value (required): The Cart of Wonder


## Language Override Resource (Base Resource)

### Properties

- Include Language Override Base Resource
- date_created: 2015-05-21T14:46:15-0700
- date_modified: 2015-05-21T14:46:15-0700