## Link (object)
Link object specifies a link to a target resource.

### Properties

- `href` (string, required) - The link URI or URI template

- `templated` (boolean) - Indicates if the href attribute contains a URI Template

- `type` (string) - Gives a hint on the expected media type of the target resource

- `deprecation` (boolean) - Indicates that the link is deprecated

- `name` (string) - A secondary key for selecting one out of multiple links

- `profile` (string) - A URI providing a hint about the profile of the target resource

- `title` (string) - A label for the link

- `hreflang` (string) - A BCP 47 language tag identifying the language of the target resource