## Payment Method Set Base Resource (object)

### Properties
- `gateway_uri`: `https://api-sandbox.foxycart.com/payment_gateways/6`
- `description` (required): `Default Payment Method Set`
- `is_live` (boolean): false
- `is_purchase_order_enabled` (boolean): false


## Payment Method Set Resource (Base Resource)

### Properties
- Include Payment Method Set Base Resource
- date_created
- date_modified