## Payment Resource (Base Resource)

### Properties

- `type`: `plastic`
- `gateway_type`
- `processor_response`
- `processor_response_details`
- `purchase_order`
- `cc_number_masked`: `xxxxxxxxxxxx1111`
- `cc_type`: `Visa`
- `cc_exp_month`: `12`
- `cc_exp_year`: `2020`
- `fraud_protection_score` (number): 0
- `paypal_payer_id`
- `amount` (number): 0
- `date_created`
- `date_modified`