## Payment Method Set Hosted Payment Gateway Base Resource (object)

### Properties

- `payment_method_set_uri`: `https://api-sandbox.foxycart.com/payment_method_sets/6`
- `hosted_payment_gateway_uri`: `https://api-sandbox.foxycart.com/hosted_payment_gateways/390`


## Payment Method Set Hosted Payment Gateway Resource (Base Resource)

### Properties

- Include Payment Method Set Hosted Payment Gateway Base Resource 
- date_created
- date_modified