## Payment Method Expiring Resource (Base Resource)

### Properties

- `months_before_expiration`: 75
- `first_name`: `Test`
- `last_name`: `User`
- `email`: `luke.stokes+apitest998@example.com`
- `cc_type`: `Visa`
- `cc_number_masked`: `xxxxxxxxxxxx1111`
- `cc_exp_month`: `12`
- `cc_exp_year`: `2020`
- `date_created`: null
- `date_modified`: `2013-08-16T14:13:54-0700`