## Shipment Resource (Base Resource)

### Properties

- `address_name`: `Default Shipping Address`
- `first_name`: `John`
- `last_name`: `Doe`
- `company`
- `address1`: `1234 Anystreet`
- `address2`
- `city`: `NASHVILLE`
- `region`: `TN`
- `postal_code`: `37211`
- `country`: `US`
- `phone`: `555-555-55555`
- `shipping_service_id`: 55
- `shipping_service_description`: `FedEx Home Delivery`
- `total_item_price` (number): 10
- `total_tax` (number): 1.99
- `total_shipping` (number): 11.29
- `total_price` (number): 23.28
- `date_created`: `2015-04-15T08:46:39-0700`
- `date_modified`: `2015-04-15T08:46:39-0700`