## Store Resource (Base Resource)

### Properties

- Include Store Base Resource 
- `is_active`: false
- `first_payment_date`: null
- `date_created`: `2010-04-24T19:25:02-0700`
- `date_modified`: `2013-07-19T11:47:26-0700`
## Store Base Resource (object)

### Properties

- `store_version_uri`: `https://api.foxycart.com/property_helpers/store_versions/20`
- `store_name` (required): `Example Store`
- `store_domain` (required): `example`
- `use_remote_domain`: false
- `store_url` (required): `https://example.com/catalog`
- `receipt_continue_url`: `http://www.example.com/thankyou`
- `store_email` (required): `someone@example.com`
- `from_email`: `helpdesk@example.com`
- `postal_code` (required): `37211`
- `region` (required): `TN`
- `country` (required): `US`
- `locale_code`: `en_US`
- `hide_currency_symbol`: false
- `hide_decimal_characters`: false
- `use_international_currency_symbol`: false
- `language`: `english`
- `logo_url`: ``
- `checkout_type`: `default_account`
- `bcc_on_receipt_email`: false
- `use_webhook`: true
- `webhook_url`: `http://example.com/my_webhook_script`
- `webhook_key`: `some super secure password your mom could not not guess`
- `use_cart_validation`: false
- `use_single_sign_on`: false
- `single_sign_on_url`: `http://example.com/my_single_sign_on_script`
- `use_email_dns`: false
- `customer_password_hash_type`: `phpass`
- `customer_password_hash_config`: `8`
- `features_multiship`: false
- `shipping_address_type`: `residential`
- `timezone`: `America/Chicago`
- `unified_order_entry_password`: `here I am, buying all your stufz`
- `affiliate_id`: 0