## Store Shipping Method Base Resource (object)

### Properties

- `shipping_method_uri`: `https://api-sandbox.foxycart.com/property_helpers/shipping_methods/1`
- `shipping_container_uri`: `https://api-sandbox.foxycart.com/property_helpers/shipping_containers/3`
- `shipping_drop_type_uri`: `https://api-sandbox.foxycart.com/property_helpers/shipping_drop_types/7`
- `accountid`: null
- `password`
- `meter_number`
- `authentication_key`
- `use_for_domestic` (boolean): false
- `use_for_international` (boolean): false

## Store Shipping Method Resource (Base Resource)

### Properties

- Include Store Shipping Method Base Resource 
- date_created
- date_modified