## Store Version Resource (Base Resource)

### Properties

- `version` - `0.7.2`
- `changelog_blog_url` - `https://www.foxycart.com/blog/0.7.2`
- `changelog_url` - `https://admin.foxycart.com/v/0.7.2/changelog.html`
- `changelog_content` - `... html ...`
- `cart_types`(object)
    - `colorbox`(object)
        - `javascript_library`(object)
            - `name` - `JQuery`
            - `version` - `1.6.4`
            - `url` - `//ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js`  
        - `javascript`(array[string])          
        - `css` (array[string])      
    - `none`(object)
        - `javascript_library`(object)
            - `name` - `JQuery`
            - `version` - `1.6.4`
            - `url` - `//ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js`
        - `javascript`(array[string])
        - `css`(array[string])
- `version_date` - `2012-01-13T12:05:06-0800`
- `is_visible`(boolean) - 1
- `is_beta`(boolean) - 0
- `date_created` - `2012-01-13T12:05:06-0800`
- `date_modified` - `2012-01-13T12:05:06-0800`