## Subscription Settings Base Resource(object)

### Properties

- `automatically_charge_past_due_amount` (boolean): true

## Subscription Settings Resource (Base Resource)

### Properties

- Include Subscription Settings Base Resource
- `date_created`: `2013-08-19T10:58:39-0700`
- `date_modified`: `2013-06-06T15:26:07-0700`