## Tax Item Category Base Resource (object)

### Properties

- `item_category_uri` (required): `https://api-sandbox.foxycart.com/item_categories/13`
- `tax_uri` (required): `https://api-sandbox.foxycart.com/taxes/1672`


## Tax Item Category Resource (Base Resource)

### Properties

- Include Tax Item Category Base Resource 
- date_created
- date_modified