## Template Set Base Resource (object)

### Properties
- `cart_template_uri` (required): `https://api-sandbox.foxycart.com/cart_templates/14`
- `cart_include_template_uri` (required): `https://api-sandbox.foxycart.com/cart_include_templates/16`
- `checkout_template_uri` (required): `https://api-sandbox.foxycart.com/checkout_templates/18`
- `receipt_template_uri` (required): `https://api-sandbox.foxycart.com/receipt_templates/20`
- `email_template_uri` (required): `https://api-sandbox.foxycart.com/email_templates/10`
- `code` (required): `DEFAULT`
- `description` (required): `Default Template Set`
- `language` (required): `english`
- `locale_code` (required): `en_US`
- `config` (required)

## Template Set Resource (Base Resource)

### Properties
- Include Template Set Base Resource
- date_created
- date_modified