## Timezone Resource (Base Resource)

### Properties

- message: The values listed here are the correct values for the Store timezone field. The values are listed in a values => timezone => timezone format.
- values(object)
    
    - timezone (array)
        - (object)
            - timezone
            - description