## Token Resource

### Properties

- access_token (string)
- expires_in (number)
- token_type : bearer
- scope(enum)
    - `client_full_access` 
    - `user_full_accessOAuth`
    - `store_full_acesss`
    
- refresh_token (string)