## Transaction Base Resource (object)

### Properties

- `id`: 3820290
- `is_test` (boolean): true
- `hide_transaction` (boolean): false
- `data_is_fed` (boolean): true
- `transaction_date`: `2013-06-06T17:26:07-05:00`
- `locale_code`: `en_US`
- `customer_first_name`: `Test`
- `customer_last_name`: `User`
- `customer_email`: `testing@example.com`
- `customer_ip`: `10.1.248.210`
- `ip_country`
- `total_item_price` (number): 10
- `total_tax` (number): 1.9
- `total_shipping` (number): 0
- `total_future_shipping` (number): 0
- `total_order` (number): 11.9
- `status` (enum[string])
    - approved
    - authorized
    - declined
    - pending
    - rejected
- `date_created`: null
- `date_modified`: `2013-06-06T15:26:07-0700`

## Transaction Resource (Base Resource)

### Properties

- Include Transaction Base Resource