## Transaction Custom Field Base Resource (object)

### Properties

- `name` (required): `Marketing_Opt_In`
- `value` (required): `1`
- `is_hidden` (boolean): false

## Transaction Custom Field Resource (Base Resource)

### Properties

- Include Transaction Custom Field Base Resource 
- date_created
- date_modified