## UserAccess Base Resource (object)

### Properties

- user_uri (string, required)
- store_uri (string, required)
- `is_default_store` (boolean)
 
## UserAccess Resource (Base Resource)

### Properties

- Include UserAccess Base Resource 
- date_created
- date_modified