## User Resource (Base Resource)

### Properties

- Include User Base Resource 
- `date_created`: `2007-05-23T16:09:12-0700`
- `date_modified`: `2013-07-10T22:37:49-0700`

## User Base Resource (object)

### Properties

- `first_name` (required) : `John`
- `last_name` (required) : `Doe`
- `email` (required) : `john.doe@example.com`
- `phone`: `555-555-5555`
- `affiliate_id`: 0
- `is_programmer`: true
- `is_front_end_developer`: false
- `is_designer`: false
- `is_merchant`: true